/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToMarkRouteImport } from './routes/_authenticated/to-mark'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedCoursesIdRouteImport } from './routes/_authenticated/courses.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToMarkRoute = AuthenticatedToMarkRouteImport.update({
  id: '/to-mark',
  path: '/to-mark',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedCoursesIdRoute = AuthenticatedCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/to-mark': typeof AuthenticatedToMarkRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/export': typeof AuthenticatedExportRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/to-mark': typeof AuthenticatedToMarkRoute
  '/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/to-mark': typeof AuthenticatedToMarkRoute
  '/_authenticated/courses/$id': typeof AuthenticatedCoursesIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/export'
    | '/sessions'
    | '/students'
    | '/to-mark'
    | '/courses/$id'
    | '/documents/$id'
    | '/sessions/$id'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/export'
    | '/sessions'
    | '/students'
    | '/to-mark'
    | '/courses/$id'
    | '/documents/$id'
    | '/sessions/$id'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/export'
    | '/_authenticated/sessions'
    | '/_authenticated/students'
    | '/_authenticated/to-mark'
    | '/_authenticated/courses/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/to-mark': {
      id: '/_authenticated/to-mark'
      path: '/to-mark'
      fullPath: '/to-mark'
      preLoaderRoute: typeof AuthenticatedToMarkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/courses/$id': {
      id: '/_authenticated/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AuthenticatedCoursesIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesIdRoute: typeof AuthenticatedCoursesIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesIdRoute: AuthenticatedCoursesIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedToMarkRoute: typeof AuthenticatedToMarkRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedToMarkRoute: AuthenticatedToMarkRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
